# Generated by Django 5.1.3 on 2024-11-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Модель телефона')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('gb', models.CharField(max_length=50, verbose_name='Количество памяти')),
                ('camer', models.CharField(max_length=50, verbose_name='Количество мегапикселей в камере')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата публикации товара')),
            ],
        ),
    ]
