# Generated by Django 4.0.5 on 2024-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_log_psw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=15, verbose_name='Login')),
                ('psw', models.IntegerField(verbose_name='Pasword')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
    ]
