# Generated by Django 4.0.5 on 2024-11-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_log_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_log_psw',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
