# Generated by Django 4.0.5 on 2024-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_log_psw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='img',
            field=models.ImageField(blank=True, upload_to='myapp/static/img'),
        ),
        migrations.AlterField(
            model_name='users_log_psw',
            name='psw',
            field=models.IntegerField(verbose_name='Password'),
        ),
    ]
