# Generated by Django 4.0.5 on 2024-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_katalog_img_alter_users_log_psw_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='des',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание товара'),
        ),
    ]
