# Generated by Django 4.0.5 on 2024-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_katalog_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='des',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание товара'),
        ),
    ]
